apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyweather-backend-deployment
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: pyweather-backend
        image: tunzor/pyweather-backend:1.0
        ports:
        - containerPort: 5003