kind: Service
apiVersion: v1
metadata:
  name: pynado-service
spec:
  type: LoadBalancer
  selector:
    app: pynado
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pynado-deployment
  labels:
    app: pynado
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pynado
  template:
    metadata:
      labels:
        app: pynado
    spec:
      containers:
      - name: pynado
        image: gcr.io/devops-236523/pynado:latest
        ports:
        - containerPort: 5000
